### ISSUE TITLE
Inserting a disk as a Disk Image (.ssd) is seen in MMBExplorer always shows 'zero bytes free' and disk is not seen when access using BBC Micro

### ISSUE THREAD

**Issue by NonDualChris** [robcfg/retrotools#13]
Hi
I am adding disks (.ssd files) into BEEB.MMB using MMBExploere version 1.3.1.
The files range in size from 49K - 182k.
Each time the disk is added, the display at the bottom of the disk contents window always reads 'Free Space 0', despite the data on the disk being much less than 204288 bytes allowed - see example.
Also, and more of a problem, the disks are not seen when using a real BBC micro with MMFS 1.55 and a working SD card reader.

The files are there. Restarting MMB Explorer and reloading the BEEB.MMB shows them there. But zeo bytes free and unreadable by my main machine.
Thank you for any assistance and best wishes
Chris
![example](https://github.com/user-attachments/assets/e8b075fd-0004-4e6f-aa90-ec9c2a7d493e)

**Comment by robcfg** [comment]
Hi Chris,

Could you upload here the JJRMusic1 ssd file shown on your picture?

That would help a lot to debug the issue.

Thanks!

**Comment by robcfg** [comment]
Regarding the ssd file itself, what is shown is what is actually on the disk image.
See the attached screenshot. On the Hex viewer you can see that the files displayed are actually the ones in the disk allocation table, so neither is the disk image corrupt nor does it contain all the files you expected.
<img width="665" alt="JJRMusic1_Contents" src="https://github.com/user-attachments/assets/85efe071-57ca-4526-ad25-ca50af675249">

I reconstructed a SSD disk image with all the files for you to try. Some may not work as I don't know all the Load and Exec addresses, but as the majority has the same, I used the addresses for all the files but the ones that are different.
Please give it a try!
[JJRGOOD.SSD.zip](https://github.com/user-attachments/files/16256236/JJRGOOD.SSD.zip)

Other than that, MMBExplorer is working as expected and I can see the contents of the disk in an emulator.

It may fail to boot because of the boot configuration as it expects a file in a certain directory which is not present.

Cheers,
Rob

**Comment by NonDualChris** [comment]
Thank you for your assistance, Rob.
Sorry if I have wasted your time here.
All files were downloaded from this website:

http://www.mdfsnet.f9.co.uk/Software/Music/

Of course, I assumed that the SSD and the ZIP files were good to be used straightaway.
That file you sent works correctly - Thank you.

All the very best
Chris

**Comment by robcfg** [comment]
No worries, I'm glad I could help you!

Cheers,
Rob
